apiVersion: v1
kind: Service
metadata:
  name: fleetservice-api-service
  namespace: default
  labels:
    app: fleetservice-api
spec:
  selector:
    app: fleetservice-api
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
---
# LoadBalancer service for API Management access
# Provides public IP for external access via API Management
apiVersion: v1
kind: Service
metadata:
  name: fleetservice-api-loadbalancer
  namespace: default
  labels:
    app: fleetservice-api
  annotations:
    # LoadBalancer required for API Management connectivity
    service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: "/health"
spec:
  selector:
    app: fleetservice-api
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  type: LoadBalancer