name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  AZURE_RESOURCE_GROUP: rg-vehicle-rental-dev
  AZURE_LOCATION: eastus
  REGISTRY_NAME: crvehiclerentaldev

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Setup .NET
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    # Setup Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: src/web/vehicle-rental-web/package-lock.json

    # Build and test backend
    - name: Restore .NET dependencies
      run: dotnet restore src/services/VehicleRentalSystem.sln

    - name: Build .NET solution
      run: dotnet build src/services/VehicleRentalSystem.sln --no-restore --configuration Release

    - name: Run .NET tests
      run: dotnet test tests/unit/FleetService.UnitTests --configuration Release --no-build --verbosity normal

    # Build frontend
    - name: Install npm dependencies
      run: npm ci
      working-directory: src/web/vehicle-rental-web

    - name: Build React app
      run: npm run build
      working-directory: src/web/vehicle-rental-web

    # Publish backend for deployment
    - name: Publish .NET API
      run: dotnet publish src/services/FleetService/FleetService.Api/FleetService.Api.csproj --configuration Release --output ./publish

    # Upload build artifacts
    - name: Upload backend artifacts
      uses: actions/upload-artifact@v4
      with:
        name: backend-build
        path: ./publish/

    - name: Upload frontend artifacts
      uses: actions/upload-artifact@v4
      with:
        name: frontend-build
        path: src/web/vehicle-rental-web/build/

  infrastructure:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v4

    # Setup Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.6.0

    # Azure Login
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Create Terraform Backend Storage (idempotent)
    - name: Create Terraform Backend Storage
      run: |
        # Create resource group for terraform state (if not exists)
        az group create --name rg-terraform-state --location eastus --output none || true

        # Create storage account for terraform state (if not exists)
        az storage account create \
          --name stterraformvehicle \
          --resource-group rg-terraform-state \
          --location eastus \
          --sku Standard_LRS \
          --output none || true

        # Create container for terraform state (if not exists)
        az storage container create \
          --name tfstate \
          --account-name stterraformvehicle \
          --output none || true

    # Terraform Init
    - name: Terraform Init
      run: terraform init
      working-directory: terraform
      env:
        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    # Terraform Plan
    - name: Terraform Plan
      run: terraform plan
      working-directory: terraform
      env:
        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        TF_VAR_resource_group_name: ${{ env.AZURE_RESOURCE_GROUP }}
        TF_VAR_location: ${{ env.AZURE_LOCATION }}
        TF_VAR_registry_name: ${{ env.REGISTRY_NAME }}
        TF_VAR_client_id: ${{ secrets.AZURE_CLIENT_ID }}
        TF_VAR_client_secret: ${{ secrets.AZURE_CLIENT_SECRET }}
        TF_VAR_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
        TF_VAR_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    # Intelligent Resource Import (for idempotent execution)
    - name: Import Existing Resources
      run: |
        # Set environment variables for terraform commands
        export ARM_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }}
        export ARM_CLIENT_SECRET=${{ secrets.AZURE_CLIENT_SECRET }}
        export ARM_TENANT_ID=${{ secrets.AZURE_TENANT_ID }}
        export ARM_SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION_ID }}
        export TF_VAR_resource_group_name=${{ env.AZURE_RESOURCE_GROUP }}
        export TF_VAR_location=${{ env.AZURE_LOCATION }}
        export TF_VAR_registry_name=${{ env.REGISTRY_NAME }}
        export TF_VAR_client_id=${{ secrets.AZURE_CLIENT_ID }}
        export TF_VAR_client_secret=${{ secrets.AZURE_CLIENT_SECRET }}
        export TF_VAR_tenant_id=${{ secrets.AZURE_TENANT_ID }}
        export TF_VAR_subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}

        # Check and import existing resources
        echo "Checking for existing resources..."

        # Import Resource Group if exists
        if az group show --name "${{ env.AZURE_RESOURCE_GROUP }}" >/dev/null 2>&1; then
          echo "Resource Group exists, importing..."
          terraform import azurerm_resource_group.main "/subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/${{ env.AZURE_RESOURCE_GROUP }}" || true
        fi

        # Import Container Registry if exists
        if az acr show --name "${{ env.REGISTRY_NAME }}" >/dev/null 2>&1; then
          echo "Container Registry exists, importing..."
          terraform import azurerm_container_registry.main "/subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/${{ env.AZURE_RESOURCE_GROUP }}/providers/Microsoft.ContainerRegistry/registries/${{ env.REGISTRY_NAME }}" || true
        fi

        # Import Container Instance if exists
        if az container show --name "ci-vehicle-rental-api-dev" --resource-group "${{ env.AZURE_RESOURCE_GROUP }}" >/dev/null 2>&1; then
          echo "Container Instance exists, importing..."
          terraform import azurerm_container_group.api "/subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/${{ env.AZURE_RESOURCE_GROUP }}/providers/Microsoft.ContainerInstance/containerGroups/ci-vehicle-rental-api-dev" || true
        fi

        # Import Static Web App if exists
        SWA_ID=$(az staticwebapp list --resource-group "${{ env.AZURE_RESOURCE_GROUP }}" --query "[?name=='swa-vehicle-rental-dev'].id" -o tsv 2>/dev/null || echo "")
        if [ ! -z "$SWA_ID" ]; then
          echo "Static Web App exists, importing..."
          terraform import azurerm_static_web_app.frontend "$SWA_ID" || true
        fi

        # Import Application Insights if exists
        if az monitor app-insights component show --app "appi-vehicle-rental-dev" --resource-group "${{ env.AZURE_RESOURCE_GROUP }}" >/dev/null 2>&1; then
          echo "Application Insights exists, importing..."
          terraform import azurerm_application_insights.main "/subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/${{ env.AZURE_RESOURCE_GROUP }}/providers/Microsoft.Insights/components/appi-vehicle-rental-dev" || true
        fi

        echo "Import phase completed."
      working-directory: terraform

    # Terraform Apply
    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: terraform
      env:
        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        TF_VAR_resource_group_name: ${{ env.AZURE_RESOURCE_GROUP }}
        TF_VAR_location: ${{ env.AZURE_LOCATION }}
        TF_VAR_registry_name: ${{ env.REGISTRY_NAME }}
        TF_VAR_client_id: ${{ secrets.AZURE_CLIENT_ID }}
        TF_VAR_client_secret: ${{ secrets.AZURE_CLIENT_SECRET }}
        TF_VAR_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
        TF_VAR_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

  deploy:
    needs: [build-and-test, infrastructure]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v4

    # Download artifacts
    - name: Download backend artifacts
      uses: actions/download-artifact@v4
      with:
        name: backend-build
        path: backend-build

    - name: Download frontend artifacts
      uses: actions/download-artifact@v4
      with:
        name: frontend-build
        path: frontend-build

    # Azure Login
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Build and push Docker image
    - name: Build and push Docker image
      run: |
        az acr login --name ${{ env.REGISTRY_NAME }}
        docker build -t ${{ env.REGISTRY_NAME }}.azurecr.io/fleet-api:${{ github.sha }} -f Dockerfile .
        docker push ${{ env.REGISTRY_NAME }}.azurecr.io/fleet-api:${{ github.sha }}

    # Deploy to Azure Container Instance
    - name: Deploy to Azure Container Instance
      run: |
        # Update container instance with new image
        az container restart --name ci-vehicle-rental-api-dev --resource-group ${{ env.AZURE_RESOURCE_GROUP }}

        # Wait for container to be ready
        echo "Waiting for container to be ready..."
        sleep 30

    # Deploy frontend to Static Web App
    - name: Deploy to Azure Static Web Apps
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        action: "upload"
        app_location: "frontend-build"
        skip_app_build: true